zeel01/MonsterBlocks

- .github/workflows/main.yml
- module.json
When a new tag is pushed run a GH Action that:
1. Gets the tag and puts it into the `download` and `version` fields of the manifest
2. zips up all the relevant files
3. attaches those files to a draft release
This means you can delete your gulpfile, package.json and package-lock when you feel comfortable doing so.
> create workflow based on zeels dark desires

- monsterblock.js
Changed isMultiAttack, isSpellcasting and isInnateSpellcasting to support additional text that is sometimes included in monster blocks. These are discussed in issue #50 .
> Enhance feature name checking to support names that contain additional text.

- actor-sheet.html
This fixes issue #47 , and the whitespace that appears after versatile attacks. Also adds the comma between each additional damage type.
> Fix whitespace after versatile attacks

- monsterblock.css
`monsterblock.css` references several images from the Foundry VTT core. These break, however, if FVTT is served from somewhere other than the root directory (using `routePrefix` in `options.json`), leading to 404 errors in the console and very ugly themes.
Making the URLs relative to the CSS file's location should fix this to work regardless of any route prefix.
> Relative image URLs

- monsterblock.js
- scripts/dnd5e/MonsterBlock5e.js
As of Tokenizer 3.3.0 the constructor has changed. As of 3.3.4 I expose a new function on Tokenizer window to allow actors to be passed to Tokenizer. I suspect there is also some additional cleanup that can be done else where in the code.
> Support Tokenizer 3.3.4

- module.json
> Use `systems` rather than `system` in the manifest

- scripts/dnd5e/AttackPreper.js
In response to [this DnD 5e MR](https://gitlab.com/foundrynet/dnd5e/-/merge_requests/428) (merged in 1.5.2), it is necessary to evaluate roll expressions before passing them to `simplifyRollFormula()`. This expands terms like `@mod` to their numeric value before simplification. Otherwise, with the new `simplifyRollFormula()` that does not use the roll data, those terms get expanded to 0 and dropped.
Fixes #123
> Evaluate attack roll expressions before simplifying

- scripts/dnd5e/MonsterBlock5e.js
Advanced Macros exposes a class called Tokenizer, which gets loaded before vtta-tokenizer. Therefore call Tokenizers window binding rather than relying on the class being available to instantiate.
Thanks!
> Tokenizer call correction

- scripts/dnd5e/ResourcePreper.js
There is an error being thrown when using consumable items because of legacy getEmbeddedEntity call to actor.
> Resolved Issue #133

- scripts/dnd5e/MonsterBlock5e.js
The object for `createEmbeddedDocuments()` requires the data object from an item, not the item itself.
> Resolves Issue Quick Insert Fails #137

- lang/en.json
- scripts/dnd5e/ActionPreper.js
- scripts/dnd5e/ItemPrep.js
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/main.hbs
This pull adds a bonus action section between standard actions and reactions according the new style changes for the NPC statblock. I can't find the documentation where it stated between Actions and Reactions right now, but I do know that's where they placed it.
> Resolves issue #61 - Bonus Action Section

- scripts/dnd5e/ItemPrep.js
- scripts/dnd5e/MonsterBlock5e.js
This resolves issue #49, by allowing actions with a cost type of none to appear in the upper section of the character sheet.
> Resolves issue #49

- monsterblock.css
There's currently an issue with `text-indent` and the icons used by entity links. This fix resolves this issue.
> Fixes linked entity icons overlapping text

- lang/en.json
- monsterblock.css
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/main.hbs
This partially resolves the issue #145 . However, there is one problem I can't seem to solve. 
When there are no items for the NPC, the menu to add items doesn't show up. I'm not entirely sure how to resolve this. I was hoping maybe you could provide some insight.
You can see in this image that the **+** is not present. However, the header, or decoration that it resides on still recedes slightly as though it wants to show it, although it doesn't show up. I'm guessing this is something simple in the html that I am just missing. Or does it have to do with the .css using ::before?
> Resolves issue #145

- scripts/dnd5e/MonsterBlock5e.js
This resolves #147.
I've updated `isSpellcaster()`, `isInnateSpellcaster()`, `isWarlock()` and `hasAtWillSpells()` to all reference `item.data.data.preparation.mode` instead of `item.data.preparation.mode`.
The first three methods do not appear to be used anywhere, but I wanted to update the methods anyway as `item.data.preparation` will always be null.
> Resolves issue #147 At-will spells not appearing in Spellcasting text

- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/header/attributes/movement.hbs
This resolves #112 in 3 ways
- Always displays walk speed, even when value is 0
- Hover displayed in parenthesis after fly speed
- Changed the inline entry of values to use the built in menu (cog) the same way Armor Class and Attribute values are modified
Notes:
- It would be possible to revert the last bullet point to allow inline entry of values
- Should the cog only be visible when editing? The Armor Class and Attribute value cogs are always visible on hover, even when not editing
- If the last option is kept, I would suggest changing senses to use a cog menu as well for consistency
> Resolves issue #112 Walking speed of zero, and flying (hover) speeds do not display appropriately

- scripts/dnd5e/AttackPreper.js
This resolves #62 by using the activation condition field of the weapon when a value is entered instead of the default values of `n target(s)` calculation.
> Resolves issue #62 Use Activation Condition for Alternate Target text

- lang/en.json
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/header/attributes/damage.hbs
This resolves #54 Nonmagical attacks
- When bludgeoning, piercing, and slashing from nonmagical attacks is selected, it always appears at the end of the list
- This damage type is always preceded by a semi-colon
- Does not display a semi-colon if it is the only resistance type selected
> Resolves issue #54 Nonmagical Attacks

- monsterblock.css
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/damageRoll.hbs
- templates/dnd5e/parts/main/attack.hbs
Resolves #152 Use default rolls for Attack and Damage
- Changes both the attack and damage rolls of weapons to use the 5e system built in rolls
- Allows use of the modifiers, and selection of advantage, disadvantage and critical damage choices
- Supports use of fast-forward hotkeys built into the 5e system (Shift = normal roll, Alt = advantage / critical, Ctrl = disadvantage)
- Uses `.mousedown` as opposed to `.click` with `event.preventDefault()` to avoid highlighting text when shift + clicking text
Notes:
- Uses the current `damageRoll.hbs` part, although, I believe with the shorter syntax required, this part could be removed, and the `span` could be added to `attack.hbs`. It's almost more complicated to pass parameters to such a small part, than to just add it to the parent part. …
> Resolves #152 Use default rolls for Attack and Damage

- scripts/dnd5e/ItemPrep.js
The labels data object is not used in the features object. These could be removed for clarity in the code. Just a suggestion, feel free to close if you feel you may still use them in the future.
> Draft: removed labels from features

- lang/en.json
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/trigger.hbs
- templates/dnd5e/switches.hbs
Resolves #158 Convert all switches to the new partial 
- all toggle switches use `switch.hbs` partial
- new `trigger.hbs` partial added and used where appropriate
- reordered Hide / Show Attack and Spellcasting Description underneath Description flyout with other options
- these were the only two cases of switches having sub items, when in reality to match the formatting of secrets and inline text, they should have likely been included in the sub menu anyway
> Resolves #158 Add switch partials to switches.hbs

- lang/en.json
- scripts/Flags.js
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/header/identity.hbs
- templates/dnd5e/parts/switch.hbs
- templates/dnd5e/switches.hbs
I added this to my local copy, and thought it may be of use for the public copy, let me know what you think. This adds the ability to switch the image on the main page between the profile image and the token image. I've found sometimes the profile images I use are large and distracting, where a token image is a bit cleaner. I am not changing the image used on the bio page, as I think that image is likely always going to be the profile image.
This also has a few added benefits. You can change the token image easily from the character sheet instead of having to choose the token cog from the top of the sheet, then navigate to the appearance tab of the token menu to set it. You can also use this to open the token image on screen and share it with the players; this is not something you can …
> Add switch to show token image instead of profile image

- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/header/attributes/damage.hbs
I realized that when I did the ordering of physical damage, I created a handlebars helper that was "technically" already there.
This PR removes the redundant `moblok-equals` helper, and replaces where it was used with the built in `eq` helper.
> removed redundant moblok-equals helper

- lang/en.json
- lang/fr.json
- lang/ja.json
- lang/pt-BR.json
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/featureBlock.hbs
- templates/dnd5e/parts/main/legendaryActs.hbs
- templates/dnd5e/parts/main/spellcasting.hbs
- templates/dnd5e/parts/switch.hbs
- templates/dnd5e/sectionHeader.hbs
- templates/dnd5e/switches.hbs
- Added `moblok-concat` handlebars helper
- Allows concatenation of strings
- `switch.hbs`
- now only needs a `data-control` value
- Uses `getProperty` to get the `flag` condition, and uses `moblok-concat` to generate the localization string
- `switches.hbs`
- Significantly simplified because of the changes to `switch.hbs`
- `sectionHeader.hbs`
- now only needs, or must provide, a `value / max` property for its `resource-key` value
- Visibility of the resource is now defined if a `resource-key` has been provided
- The `value` and `max` values are looked up using `getProperty` and `moblok-concat` helpers
- `collapsibleSection.hbs`
- Now only requires `resource-key` to provide access to the header resource value
- reversed the language of `hide-profile-image`, not sure if this was incorrect …
> Enhanced Lookups

- scripts/dnd5e/MonsterBlock5e.js
Closes #175 Right clicking on weapon rolls causes roll
- changed attack and damage rolls from mousedown to click event
- removes accidental rolling of attack and damage during right click
- stops shift select highlight of text (reason for mouse down previously)
- removed a couple lines of code when getting the item to roll
> Closes #175 Right clicking on weapon rolls causes roll

- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/menuItem.hbs
- Fixes saves, resistances, vulnerabilities and immunities not being able to be toggled by clicking on them due to incorrect references.
- Fixes labels for skills showing as [Object object] due to not referencing the label but the skill object itself.
- Fixes skill configuration panel not opening due to the data key not being present in the html a tag.
Not sure if these were issues only I was experiencing because I don't see any open issues on these topics but the save/skill/damage dropdowns all seemed to have bugs that prevented toggling them, caused incorrect skill labeling, and errors when trying to open skill configuration.
Tested on Version 11 Stable 315, DND System 3.0.3
> Fix several broken references relating to traits and proficiencies.

- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/header/attributes/movement.hbs
- templates/dnd5e/parts/header/attributes/senses.hbs
Fixes #218. Selecting the "Automatic" unit option under movement or senses caused movement.units to return null. I've resolved it by just using the system's first unit option if the units field is null.
> Resolves #218 Senses show "null" instead of correct unit 

- module.json
- scripts/dnd5e/Flags5e.js
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/featureBlock.hbs
- templates/dnd5e/parts/main/attack.hbs
This PR along with [this one](https://github.com/zeel01/input-expressions/pull/11) adds support for dnd5e system v3 and foundry v12.
- `_onItemCreate` has been removed, so I had to add a custom handler.
- All other handlers for skills, saves, etc weren't working either, so I added custom handlers as well. Not sure if it's the best approach, but couldn't get it to work otherwise and didn't see any methods from the base 5e sheet that could be used for this.
- I had to add a `getLanguageChecklist` method, because the shape of `CONFIG.DND5E.languages` has changed. It does not have a label (but the others such as damage, conditions, etc, do) and it can contain `children` for subgroups.
- dnd5e v3 enrichers seem to be working fine just by calling `TextEditor.enrichHTML` asynchronously in …
> add support for dnd5e v3 and foundry v12

- scripts/dnd5e/MonsterBlock5e.js
This issue (#191) was caused by event.target.currentSrc (local URL) being used to display the image popout. The result was that foundry attempted to display the image using a localhost url on remote machines when sharing. 
Looking at the code behind the "View Character Artwork" option in the actor directory suggests that actor.img should be used instead, so that's what I went with.
Additionally, I implemented a fix for the issue where the image edit dialog would pop up on left click alongside the image popout. This is done by simply unbinding all click events on the relevant element, which is admittedly not the cleanest solution, but it seems to be working as expected.
> Resolves #191 'Show to Players' button when showing actor artwork from MonsterBlocks doesn't load the image

- scripts/dnd5e/CastingPreper.js
- scripts/dnd5e/InnateSpellbookPrep.js
- scripts/dnd5e/MonsterBlock5e.js
- templates/dnd5e/parts/header/attributes/saves.hbs
- templates/dnd5e/parts/main/legendaryActs.hbs
- Fixed description enrichment (#241);
- Fixed Legendary Actions section title (#242);
- Fixed old reference to .data and additional deprecations (#243);
- Fixed reference to ability.save (now .save.value in 4.x) (#245);
- Fixed issue with inventory items (#247).
- Improved innate spellcasting management with initial support for cast activities (like in the MM2024) (#246).
Hopefully submitting a PR on a PR branch is not too weird. 
I will add a note in #246 to explain a little more about that one, but part of the problem there is a new style of creating spellcasting features (with cast activities inside, instead of actuall spell items), with a current system limitation preventing the spellbook to be populated. The changes made here still bring us in a better place to work with that.
> Misc fixes to the most recent issues

- module.json
- Updated input-expression submodule
- Removed obsolete `allowBugReporter` and `author` (we already had the new `authors`) keys from module.json.
- Updated verified dnd5e version in module.json
> Updated input-expression submodule, removed obsolete manifest keys
